name: apmtools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - nomkl
  - apav
  - paraprobe-toolbox
  - compositionspace
  - pip
  # pip packages (installed into the same env)
  # - pip:
    # add more if needed